from configparser import ConfigParser

default_config = """
[Galaxy]

[Spiral galaxy]

[Elliptical galaxy]

[Systems]
# Minimum distance between systems (in parsecs)
Minimum distance = 1

# How many stars exist in a system, generated by a normal distribution. The
# generated will be bounded to the interval [1, inf)
Stars per system mean = 1
Stars per system std = 0.5

# How many planets exist in a system, generated by a normal distribution. The
# generated will be bounded to the interval [0, inf)
Planets per system mean = 10
Planets per system std = 5

# How many moons exist per planet, generated by a normal distribution. The
# generated values will be bounded to the interval [0, inf)
Moons per planet mean = 4
Moons per planet std = 4

[Stars]
# Spectral type proportion of appearance in a typical galaxy
Spectral type O proportion = 0.0000003
Spectral type B proportion = 0.0013
Spectral type A proportion = 0.006
Spectral type F proportion = 0.03
Spectral type G proportion = 0.076
Spectral type K proportion = 0.121
Spectral type M proportion = 0.7645
"""
config = ConfigParser(allow_no_value=True)
config.read_string(default_config)
